### ISSUE TITLE
CI: mypy is not executed on Python 3.10, 3.11, and 3.12

### ISSUE THREAD

**Issue by Mulugruntz** [Mulugruntz/celery-pubsub#270]
The culprit seems to be 

```yml
    - name: Check with mypy
      if: ${{ !startsWith(matrix.python-version, 'pypy') && matrix.python-version >= '3.7' }}
      run: mypy
```

The comparison is string to string. Therefore `3.10 < 3.7` (1<7).

The version comparison can be entirely removed, as we don't support < 3.7 anymore.

```diff
    - name: Check with mypy
-      if: ${{ !startsWith(matrix.python-version, 'pypy') && matrix.python-version >= '3.7' }}
+      if: ${{ !startsWith(matrix.python-version, 'pypy') }}
      run: mypy
```
